spring:
  application:
    name: otp-service

server:
  port: ${PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: false
    instance-id: "${spring.application.name}:${server.port}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
